Repository auth0/express-openid-connect, pull requests merged in 2019-09, with the labels that each got.

#19 Setup the CODEOWNERS for pull request reviews
  .github/CODEOWNERS
Labels: review:tiny

#12 feat: bump openid-client
  .travis.yml
  API.md
  lib/client.js
  lib/getUser.js
  middleware/auth.js
  package-lock.json
  package.json
  test/callback_route_form_post.tests.js
  test/fixture/cert.js
Labels: CH: Changed

#17 Remove debugging callbacks
  API.md
  lib/context.js
  middleware/auth.js
  package-lock.json
  package.json
Labels: CH: Removed, review:small

#23 Add telemetry to HTTP requests
  lib/client.js
  package-lock.json
  test/client.tests.js
  test/fixture/well-known.json
Labels: CH: Added, review:small
