Repository auth0/express-openid-connect, pull requests merged in 2020-02, with the labels that each got.

#61 Update README.md for secure channels
  README.md
Labels: review:tiny

#62 Move to CircleCI: Run lint and generate coverage
  .circleci/config.yml
  .travis.yml
  README.md
  codecov.yml
  package-lock.json
  package.json
Labels: review:small

#63 Register Express as a peer dependency
  README.md
  package.json
Labels: review:tiny

#65 Update TS defs for config functions
  index.d.ts
  middleware/auth.js
Labels: CH: Added, review:tiny

#66 Update refresh token example with how to refresh session
  EXAMPLES.md
Labels: review:tiny

#67 Release 0.7.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: review:tiny

#69 [SDK-1383] Updated readme.md to include beta wording
  README.md
Labels: review:tiny

#70 Release 0.8.0
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: review:tiny
