Repository auth0/express-openid-connect, pull requests merged in 2020-01, with the labels that each got.

#47 Add path validation
  lib/config.js
  middleware/auth.js
  test/auth.tests.js
Labels: CH: Added, review:small

#48 Generate test session during tests
  test/appSession.tests.js
  test/fixture/sessionEncryption.js
Labels: review:tiny

#51 Update hapi/joi to 15.x; update other deps to minor/patch
  package-lock.json
  package.json
  test/callback_route_form_post.tests.js
Labels: CH: Changed, review:tiny

#52 Fix TS definition for appSessionSecret
  index.d.ts
Labels: CH: Fixed, review:tiny

#40 Fix post logout redirect, add config for default
  .eslintrc.json
  API.md
  index.d.ts
  lib/config.js
  lib/context.js
  test/logout.tests.js
Labels: CH: Fixed

#56 Update hapi to v16 and fix breaking changes
  lib/config.js
  package-lock.json
  package.json
  test/invalid_params.tests.js
Labels: CH: Changed, review:small

#59 Cleanup middleware in auth.js
  middleware/auth.js
Labels: review:small
