Repository auth0/express-openid-connect, pull requests merged in 2020-05, with the labels that each got.

#95 Fix returnTo on Login
  lib/context.js
  test/requiresAuth.tests.js
Labels: CH: Fixed, review:tiny

#94 Cookie options should be applied when clearing the cookie as well as setting the cookie
  lib/appSession.js
  package-lock.json
  package.json
  test/fixture/server.js
  test/logout.tests.js
Labels: CH: Fixed, review:medium

#97 Remove .env from README
  README.md
Labels: review:tiny

#98 Update README.md
  README.md
Labels: review:tiny
