Repository auth0/express-openid-connect, pull requests merged in 2020-03, with the labels that each got.

#73 Release 0.8.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: review:tiny

#74 [SDK-1087] Fix case where APP_SESSION_SECRET is set and appSession is not
  lib/config.js
  test/config.tests.js
  test/invalid_params.tests.js
Labels: review:small

#77 Check idTokenAlg configuration is not overridden by discover server
  package-lock.json
  package.json
  test/client.tests.js
Labels: CH: Security, review:small

#78 [SDK-1466] Allow to opt-out from sending SDK Telemetry - by setting `enableTelem…
  API.md
  EXAMPLES.md
  index.d.ts
  lib/client.js
  lib/config.js
  test/client.tests.js
Labels: CH: Added, review:tiny

#80 Change the default session duration to 1 day
  API.md
  index.d.ts
  lib/config.js
  test/config.tests.js
Labels: review:small

#79 [SDK-1468] Add a note on hiding error details from the client
  README.md
Labels: review:tiny
