Repository auth0/express-openid-connect, pull requests merged in 2020-12, with the labels that each got.

#159 [SDK-2155] Default cookie.secure config to the protocol of baseURL
  FAQ.md
  README.md
  index.d.ts
  lib/appSession.js
  lib/config.js
  lib/transientHandler.js
  middleware/attemptSilentLogin.js
  test/appSession.tests.js
  test/attemptSilentLogin.tests.js
  test/callback.tests.js
  test/config.tests.js
  test/logout.tests.js
  test/requiresAuth.tests.js
  test/setup.js
  test/transientHandler.tests.js
Labels: review:medium

#171 afterCallback Hook [SDK-1728]
  index.d.ts
  lib/config.js
  middleware/auth.js
  test/callback.tests.js
Labels: CH: Added

#168 Move transient cookies into one cookie [SDK-1908]
  lib/context.js
  middleware/auth.js
  test/callback.tests.js
  test/login.tests.js
Labels: CH: Changed, review:medium
