Repository auth0/express-openid-connect, pull requests merged in 2022-06, with the labels that each got.

#362 Update EXAMPLES.md
  EXAMPLES.md
Labels: review:tiny

#366 Update dependencies
  package-lock.json
Labels: review:tiny, dependencies

#369 Update index.d.ts
  index.d.ts
Labels: review:tiny

#371 discovery errors should be handled in express middleware
  lib/context.js
  test/login.tests.js
  test/logout.tests.js
  test/setup.js
Labels: review:small

#373 Replace experimental express-oauth2-bearer
  examples/api.js
  package-lock.json
  package.json
Labels: review:small
